name: Psalm Security Scan

on:
  push:
    branches:
      - main

jobs:
  psalm-security-scan:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm – Security Scanner for PHP
        uses: psalm/psalm-github-security-scan@1.4.0

      - name: installing updates
        run: |
          sudo apt-get update
          sudo apt-get install php-soap php-gd php-zip

        
      - name: Import Security Analysis results into GitHub Security Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
