name: PHP Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write  # required to upload SARIF reports

jobs:
  php-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, curl, json, zip
        coverage: none

    - name: Install Dependencies
      run: |
        composer require --dev phpmd/phpmd friendsofphp/php-cs-fixer phpstan/phpstan

    - name: Run PHP Mess Detector (PHPMD)
      run: |
        mkdir -p reports
        ./vendor/bin/phpmd --reportfile reports/phpmd.sarif -- src xml rulesets/cleancode.xml,rulesets/codesize.xml,rulesets/unusedcode.xml
    - name: Upload SARIF Report to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/phpmd.sarif
